export const FETCH_THEME_LIST_DATA = 'FETCH_THEME_LIST_DATA';
export const FETCH_THEME_LIST_DATA_SUCCESS = 'FETCH_THEME_LIST_DATA_SUCCESS';
export const FETCH_THEME_LIST_DATA_FAILURE = 'FETCH_THEME_LIST_DATA_FAILURE';

export const FETCH_THEME_ITEM_DATA = 'FETCH_THEME_ITEM_DATA';
export const FETCH_THEME_ITEM_DATA_SUCCESS = 'FETCH_THEME_ITEM_DATA_SUCCESS';
export const FETCH_THEME_ITEM_DATA_FAILURE = 'FETCH_THEME_ITEM_DATA_FAILURE';

export const UPDATE_THEME = 'UPDATE_THEME';
export const UPDATE_THEME_SUCCESS = 'UPDATE_THEME_SUCCESS';
export const UPDATE_THEME_FAILURE = 'UPDATE_THEME_FAILURE';